### ISSUE TITLE
name 'path' is not defined

### ISSUE THREAD

**Issue by LaikaSa** [nicolai256/Stable-textual-inversion_win#16]
When I run the third step on google colab it gave me this:
![Untitled](https://user-images.githubusercontent.com/112873279/188450225-879b3465-95e6-4eb1-99d8-1fb11b9cb5cb.png)
I already tried to add ''from pathlib import Path'' on top but no luck, still the same error

**Comment by nicolai256** [comment]
try putting the `dirs = os.listdir(path)` thing **under** `path=path_to_input_images`

**Comment by LaikaSa** [comment]
That did the trick but a new error appeared:
![image](https://user-images.githubusercontent.com/112873279/188736726-a167eda7-1f6d-4e1d-8cd5-01a21b250a15.png)
However, I got another version of your notebook that worked: https://colab.research.google.com/drive/1bnPJzT-dN0DUR50Z3GwtMtTKLm03o2c1?usp=sharing&authuser=5#scrollTo=WHlruknRbsHJ
The one with errors is on GitHub, did you forget to update the link to the latest version?

**Comment by LaikaSa** [comment]
nvm just delete that line will do the trick
