### ISSUE TITLE
stuck at installing pip dependencies (Windows 10)

### ISSUE THREAD

**Issue by XodrocSO** [nicolai256/Stable-textual-inversion_win#3]
I suspect this probably doesn't have anything to do with textual inversion or your fork, but posting just in case it's an easy issue to resolve.  

So trying to create  a conda env from enviromnent.yaml simply get's stuck forever at "Installing Pip Dependencies", it's been hours.

Earlier I had no issue doing the same with the original textual inversion, only to discover it couldn't run in windows.  I have also have stable diffusion running just fine locally on windows in a conda environment.

Some background if you're interested in extra nonsense about how I probably broke everything:

So then I decided to try the WSL route, went through the trouble of setting up ubuntu and miniconda/miniforge there only to find out that even though I was in a fresh environment it was still somehow looking at windows pytorch files which had a mismatch install for pytorch on cuda 11.3 and torchvision on cuda 11.6, and no matter how many times I tried to upgrade, reinstall or downgrade pytorch, it kept giving me the same message.. then I downgraded the windows installation and ran into other issues I couldn't resolve in ubuntu.

Then I see windows version fork by nicolai256! and think "screw ubuntu"... but now, magically I can't even create a new environment from environment.yaml successfully(edited the name of the environment to be unique)..

Trying some other things, like changing the pip version in the .yaml got me further only for it to throw a bunch of conflict messages and fail to set things up..  Just seems like an endless rabbit-hole, but maybe it's a simple fix I haven't found, or maybe I should look to nuke everything python related and start over.  I tried to install things from the yaml manually, but suspect I missed something there too.  

-a non programmer, with experience compiling C++ apps but new to python.

**Comment by nicolai256** [comment]
hmm that's weird, u can edit the environment name inside the environment.yaml file, u need to change `name: ldm` to `name: ldm2` if you want to create a new env or try `conda env remove -n ldm` in command prompt and reinstall

the pip installs are correct, so don't change those

let me know how it goes

**Comment by XodrocSO** [comment]
No luck doing that, still gets stuck at installing dependencies.

The only thing I could find searching around with someone getting stuck in general is this: https://github.com/conda/conda/issues/10807

But it didn't provide a solution that works for me.

**Comment by nicolai256** [comment]
weird.. have u tried deleting all the environments and then uninstalling and reinstalling conda?

**Comment by vini2003** [comment]
Similar issue. Completely clean environment, no previous packages, stuck in `Installing pip dependencies: ...working...` (using `-v` for verbosity).

Out of ideas at this point.

**Comment by nicolai256** [comment]
weird
is ti possible to install another environment.yml? not from my repo?
if u place replace the environment.yml from here https://github.com/lstein/stable-diffusion with the one in mine does it change anything?

**Comment by vini2003** [comment]
It doesn't work either. Seems to be a new issue?
https://github.com/lstein/stable-diffusion/issues/63

**Comment by hlky** [comment]
This could be related to an issue my users have been having. Essentially pip gets stuck when the ./src folder is not empty, this happens when you are recreating the environment, the solution is to clear ./src folder first,
Alternatively try:
```
set PIP_EXISTS_ACTION=w
(in your conda prompt window)
then try conda env update -f environment.yaml

whats happening is PIP is finding something exists and it is waiting for user input, which locks up conda. So PIP_EXISTS_ACTION=w causes it to just write over and continue without user input
```

**Comment by nicolai256** [comment]
> It doesn't work either. Seems to be a new issue? [lstein/stable-diffusion#63](https://github.com/lstein/stable-diffusion/issues/63)


i just had the same issue today haha, i found a fix so ur in luck
so i fixed it by deleting folders and stuff like that
**in anaconda prompt**
`conda env remove -n ldm`
**delete these folders**
C:\ProgramData\Anaconda3\envs\ldm
C:\Users\username\.conda\envs\ldm
stable-diffusion\src

**Comment by XodrocSO** [comment]
I'll give it a try to confirm tomorrow! Been distracted with other toys.
