### ISSUE TITLE
name 'trainer' is not defined

### ISSUE THREAD

**Issue by DrakeFruit** [nicolai256/Stable-textual-inversion_win#7]
Global seed set to 23
Traceback (most recent call last):
  File "/content/Stable-textual-inversion_win/main.py", line 574, in <module>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "/content/Stable-textual-inversion_win/main.py", line 574, in <listcomp>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/Stable-textual-inversion_win/Stable-textual-inversion_win/configs/stable-diffusion/v1-finetune_colabT4.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Stable-textual-inversion_win/main.py", line 815, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

followed instructions on colab, got this error, no idea why

**Comment by nicolai256** [comment]
try now

**Comment by DrakeFruit** [comment]
> try now

how long does this usually take? I put in 45 images, though I see max_images is 15

**Comment by nicolai256** [comment]
> > try now
> 
> how long does this usually take? I put in 45 images, though I see max_images is 15

5000 iterations should be enough, depending on the similarity and amount of your images etc..
check the logs folder and see if the output test images are good enough.
as far as i'm aware of the max_images parameter doesn't work like that, it's for something else.
mine is at 15 too but the inputs in my log folder show way more so that shouldn't be a problem.

**Comment by DrakeFruit** [comment]
4300 / 5656 and im still getting eldritch horrors, do I just run it longer?

**Comment by nicolai256** [comment]
yea

**Comment by DrakeFruit** [comment]
> yea

do I just click stop when im done training? does it save if I just close the tab?

**Comment by DrakeFruit** [comment]
theres no way to resume on colab...

**Comment by nicolai256** [comment]
> 

resuming is not possible yet
