### ISSUE TITLE
google colab kicked me out due to gpu usage

### ISSUE THREAD

**Issue by DrakeFruit** [nicolai256/Stable-textual-inversion_win#8]
after running for 4 hours it kicked me out and wont let me run the colab, this also deleted all my progress in the ckpt file... any way to recover that?

**Comment by nicolai256** [comment]
no if your colab stops it stops, one of the downsides of colab

**Comment by DrakeFruit** [comment]
how do I save the files to my drive and run it from there

**Comment by nicolai256** [comment]
put the repo in ur drive and use it like that

**Comment by affanmehmood** [comment]
How often does the code save the checkpoint files?

**Comment by nicolai256** [comment]
it saves when u cancel the training

**Comment by nicolai256** [comment]
intermediate saving still has to be fixed, for now it saves every epoch tho

**Comment by affanmehmood** [comment]
This is the issue I'm facing when I try to resume the training from last.ckpt. Why is this happening?

Global seed set to 23
Running on GPUs 1
Loading model from /content/drive/MyDrive/---/checkpoints/last.ckpt
Traceback (most recent call last):
  File "/content/Stable-textual-inversion_win/main.py", line 604, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "/content/Stable-textual-inversion_win/main.py", line 37, in load_model_from_config
    sd = pl_sd["state_dict"]
KeyError: 'state_dict'

**Comment by nicolai256** [comment]
Resume doesn't work yet
